version: 0.2

phases:
  pre_build:
    commands:
      - echo "Pre-build phase"
      - apt-get update
      - apt-get install -y maven
      - apt-get install -y unzip
      # - wget -N https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
      # - unzip chromedriver_linux64.zip
      # - mv chromedriver /usr/bin/chromedriver
      # - chromedriver --version
      # - chmod +x /usr/bin/chromedriver
      # - curl -sSL https://intoli.com/install-google-chrome.sh | bash -s -- --accept-high-risk --install-dir=/usr/bin
      - ls /usr/bin
      # - mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
      - google-chrome --version && which google-chrome
      
  build:
    commands:
      - echo "Build phase"
      - mvn test -PExecuteTests
